/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import DAO.NhanVienDAO;
import javax.swing.JOptionPane;
import Helper.DialogHelper;
import Helper.ShareHelper;
import Model.NhanVien;

/**
 *
 * @author Acer
 */
public class login extends javax.swing.JFrame {

	/**
	 * Creates new form login
	 */
	public login() {
		initComponents();
		setLocationRelativeTo(null);
		setTitle("Đăng nhập");
	}

	public String ErrorMessage;
	public String CorrectMessage;

	private static boolean isPasswordCorrect(char[] input) {
		boolean isCorrect = false;

		if (input.length == 0) {
			isCorrect = true;
		}

		return isCorrect;
	}

	public boolean Validate() {
		if (txtMaNV.getText().equals("")) {
			lblErrManv.setText("Tên đăng nhập không được để rỗng");
			txtMaNV.requestFocus();
			return false;

		}
		if (isPasswordCorrect(txtmatkhau.getPassword())) {
			lblErrPassword.setText("Mật khẩu không được để rỗng");
			txtmatkhau.requestFocus();
			return false;
		}
		if (txtMaNV.getText().trim().length() < 3) {
			JOptionPane.showMessageDialog(this, "Bạn phải nhập đúng yêu cầu", "Error", JOptionPane.ERROR_MESSAGE);
			return false;
		}
		if (new String(txtmatkhau.getPassword()).trim().length() < 3) {
			JOptionPane.showMessageDialog(this, "Bạn phải nhập đúng yêu cầu", "Error", JOptionPane.ERROR_MESSAGE);
			return false;
		}
		return true;
	}

	NhanVienDAO dao = new NhanVienDAO();

	public void login() {
		lbldn.setText("Hãy thử lại!");
		String manv = txtMaNV.getText();
		String matKhau = new String(txtmatkhau.getPassword());
		try {
			NhanVien nhanVien = dao.findById(manv);

			if (nhanVien != null) {
				String matKhau2 = nhanVien.getMatKhau();
				if (matKhau.equals(matKhau2)) {

					ShareHelper.USER = nhanVien;
					new quanly().setVisible(true);
					this.dispose();
					CorrectMessage = "Đăng nhập thành công";
				} else {
					DialogHelper.alert(this, "Sai mật khẩu!");
					ErrorMessage = "Sai mật khẩu";
					lbldn.setText("Mời Đăng Nhập.");
				}
			} else {
				DialogHelper.alert(this, "Sai tên đăng nhập!");
				lbldn.setText("Mời Đăng Nhập.");
			}
		} catch (Exception e) {
			DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
			e.printStackTrace();
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		btndangnhap = new javax.swing.JButton();
		btnketthuc = new javax.swing.JButton();
		txtmatkhau = new javax.swing.JPasswordField();
		txtMaNV = new javax.swing.JTextField();
		lblErrManv = new javax.swing.JLabel();
		lblErrPassword = new javax.swing.JLabel();
		lbldn = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(0, 0, 102));

		jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/web-shield.png"))); // NOI18N

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(255, 102, 102));
		jLabel4.setText("ĐĂNG NHẬP");

		jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel5.setForeground(new java.awt.Color(255, 204, 204));
		jLabel5.setText("Tên đăng nhập");

		jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel6.setForeground(new java.awt.Color(255, 204, 204));
		jLabel6.setText("Mật khẩu");

		btndangnhap.setBackground(new java.awt.Color(0, 153, 0));
		btndangnhap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		btndangnhap.setForeground(new java.awt.Color(255, 255, 255));
		btndangnhap.setText("Đăng nhập");
		btndangnhap.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btndangnhapActionPerformed(evt);
			}
		});

		btnketthuc.setBackground(new java.awt.Color(255, 51, 0));
		btnketthuc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		btnketthuc.setForeground(new java.awt.Color(255, 255, 255));
		btnketthuc.setText("Kết thúc");
		btnketthuc.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnketthucActionPerformed(evt);
			}
		});

		txtmatkhau.setBackground(new java.awt.Color(153, 153, 255));
		txtmatkhau.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		txtmatkhau.setForeground(new java.awt.Color(255, 255, 0));
		txtmatkhau.addCaretListener(new javax.swing.event.CaretListener() {
			public void caretUpdate(javax.swing.event.CaretEvent evt) {
				txtmatkhauCaretUpdate(evt);
			}
		});

		txtMaNV.setBackground(new java.awt.Color(153, 153, 255));
		txtMaNV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		txtMaNV.setForeground(new java.awt.Color(255, 255, 255));
		txtMaNV.addCaretListener(new javax.swing.event.CaretListener() {
			public void caretUpdate(javax.swing.event.CaretEvent evt) {
				txtMaNVCaretUpdate(evt);
			}
		});

		lblErrManv.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		lblErrManv.setForeground(new java.awt.Color(255, 51, 51));

		lblErrPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		lblErrPassword.setForeground(new java.awt.Color(255, 51, 51));

		lbldn.setForeground(new java.awt.Color(255, 204, 0));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 239,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
								jPanel1Layout.createSequentialGroup().addGap(18, 18, 18).addGroup(jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
												jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(jPanel1Layout.createSequentialGroup()
																.addGroup(jPanel1Layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(jPanel1Layout.createSequentialGroup()
																				.addComponent(jLabel6)
																				.addGap(0, 0, Short.MAX_VALUE))
																		.addGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				jPanel1Layout.createSequentialGroup()
																						.addGap(0, 0, Short.MAX_VALUE)
																						.addComponent(jLabel5)))
																.addGap(18, 18, 18)
																.addGroup(jPanel1Layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		false)
																		.addComponent(txtMaNV,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				194,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(txtmatkhau,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				194,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(jPanel1Layout.createSequentialGroup()
																.addGap(110, 110, 110)
																.addGroup(jPanel1Layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.TRAILING)
																		.addComponent(lblErrManv,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				188,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(lblErrPassword,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				188,
																				javax.swing.GroupLayout.PREFERRED_SIZE))))
														.addGap(84, 84, 84))
										.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel4)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(lbldn, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(104, 104, 104))))
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(51, 51, 51)
										.addComponent(btndangnhap).addGap(48, 48, 48).addComponent(btnketthuc)
										.addGap(0, 0, Short.MAX_VALUE)))));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jLabel3).addGap(0, 6,
						Short.MAX_VALUE))
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(20, 20, 20).addComponent(jLabel4)
										.addGap(45, 45, 45))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(lbldn)
												.addGap(34, 34, 34)))
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel5))
						.addGap(8, 8, 8).addComponent(lblErrManv)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel6))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(lblErrPassword).addGap(17, 17, 17)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btndangnhap).addComponent(btnketthuc))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btndangnhapActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btndangnhapActionPerformed
		if (Validate()) {
			login();
		}

	}// GEN-LAST:event_btndangnhapActionPerformed

	private void btnketthucActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnketthucActionPerformed
		if (DialogHelper.confirm(this, "Bạn có muốn thoát khỏi ứng dụng không?")) {
			CorrectMessage = "Đã thoát";
			System.exit(0);
		}
	}// GEN-LAST:event_btnketthucActionPerformed

	private void txtMaNVCaretUpdate(javax.swing.event.CaretEvent evt) {// GEN-FIRST:event_txtMaNVCaretUpdate
		if (txtMaNV.getText().length() < 3) {
			lblErrManv.setText("Tên đăng nhập phải trên 3 kí tự");
		} else {
			lblErrManv.setText("");
		}
	}// GEN-LAST:event_txtMaNVCaretUpdate

	private void txtmatkhauCaretUpdate(javax.swing.event.CaretEvent evt) {// GEN-FIRST:event_txtmatkhauCaretUpdate
		if (txtmatkhau.getPassword().length < 3) {
			lblErrPassword.setText("Mật khẩu phải trên 2 kí tự");
		} else {
			lblErrPassword.setText("");
		}
	}// GEN-LAST:event_txtmatkhauCaretUpdate

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new login().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	public javax.swing.JButton btndangnhap;
	public javax.swing.JButton btnketthuc;
	public javax.swing.JLabel jLabel3;
	public javax.swing.JLabel jLabel4;
	public javax.swing.JLabel jLabel5;
	public javax.swing.JLabel jLabel6;
	public javax.swing.JPanel jPanel1;
	public javax.swing.JLabel lblErrManv;
	public javax.swing.JLabel lblErrPassword;
	public javax.swing.JLabel lbldn;
	public javax.swing.JTextField txtMaNV;
	public javax.swing.JPasswordField txtmatkhau;
	// End of variables declaration//GEN-END:variables
}
